### ISSUE TITLE
Some nitpicking on grammar

### ISSUE THREAD

**Issue by thirsch81** [jenkinsci/scm-sync-configuration-plugin#17]
Hi there,
when I read the message:
Error while copying file hierarchy to SCM checkouted directory
I doubted that 'checkouted' even existed as a word, and then I found this:
http://notaverb.com/checkout

**Comment by dyroffk** [comment]
:+1:  Would be helpful to include the details about what exactly failed too

**Comment by tomaswolf** [comment]
The grammar part would be fixed by PR #31.

**Comment by rodrigc** [comment]
Fixed in https://github.com/jenkinsci/scm-sync-configuration-plugin/commit/c29b6fb4cef53b885640adc08d19aef724bbb390
