### ISSUE TITLE
Bug in v0.0.8: No Commit Message Popup Window when Updating Jobs

### ISSUE THREAD

**Issue by tknerr** [jenkinsci/scm-sync-configuration-plugin#22]
Seems that this bug had been introduced in v0.0.8

The commit message popup still occurs when changing the global jenkins config, but it does not when updating a job config.

See the issue on the Jenkins-ci JIRA here:
https://issues.jenkins-ci.org/browse/JENKINS-22666

**Comment by hotterd** [comment]
had the same issue

**Comment by tomaswolf** [comment]
Would be fixed by PR #31.

**Comment by rodrigc** [comment]
Fixed in https://github.com/jenkinsci/scm-sync-configuration-plugin/commit/e995bd405450c7c5b947c0c30871781ffc56b2ad

**Comment by aviv-clover** [comment]
I see this issue on 0.0.9 too (Jenkins is 1.609.3)
