### ISSUE TITLE
SCM sync configuration plugin stopped working for new version of Jenkins 2.332.1

### ISSUE THREAD

**Issue by preddymm** [jenkinsci/scm-sync-configuration-plugin#76]
### Jenkins and plugins versions report

<details>
  <summary>Environment</summary>

  
  ```text
  Paste the output here
  ```

</details>

### What Operating System are you using (both controller, and any agents involved in the problem)?

SCM sync plugin stopped working after upgrading to the new LTS version of Jenkins.
Please fix it ASAP.

### Reproduction steps

It should get updated in the git repository.

### Expected Results

It should get updated in the git repository.

### Actual Results

It should get updated in the git repository.

**Comment by preddymm** [comment]
@rodrigc Could you please update and release the new plugin? It will be really helpful for all.

**Comment by preddymm** [comment]
@fcamblor @tomaswolf @ndeloof @johnou @jcarsique @stephenc @mhelff @mnencia @alanharder @olamy ? Please help us. We are using this plugin from last 6 years and after the recent Jenkins LTS upgrade it stopped working.

**Comment by johnou** [comment]
@preddymm is there a JIRA ticket with a stacktrace?

**Comment by preddymm** [comment]
@johnou https://plugins.jenkins.io/scm-sync-configuration/#issues
#76 is the one created by me.
I created an issue in the above link. Not sure, where to create the Jira one.

**Comment by johnou** [comment]
~https://github.com/jenkinsci/scm-sync-configuration-plugin/pull/74 may help.~ JEP still draft.

**Comment by basil** [comment]
@johnou @preddymm If the changes from #74 work, you can consider [adopting the plugin](https://www.jenkins.io/doc/developer/plugin-governance/adopt-a-plugin/) to merge and release the PR. The "[Contributing to Open Source](https://docs.google.com/document/d/1PKYIpPlRVGsBqrz0Ob1Cv3cefOZ5j2xtGZdWs27kLuw/edit#heading=h.hvd0nm6pz5o4)" workshop from DevOps World 2021 is a useful starting point for new maintainers. That document includes links to a [five part video series](https://docs.google.com/document/d/1PKYIpPlRVGsBqrz0Ob1Cv3cefOZ5j2xtGZdWs27kLuw/edit#heading=h.oz0bxvhyvna5) that illustrates many of the steps. If the plugin is crucial to your work, you may want to ask your employer to support your work efforts by allowing you to adopt the plugin.

**Comment by johnou** [comment]
@preddymm do you see an error or stacktrace in the Jenkins logs related to the plugin which explains why it stopped working?

**Comment by preddymm** [comment]
@johnou Unfortunately, it is not giving any errors in the Jenkins logs, The only issue with this plugin is it not updating in the Git repository. It was able to calculate the change in Jenkins configuration. Something was happening that it was not able to notify and update the Git repository.

The Jenkins version I am using is 2.332.1

**Comment by preddymm** [comment]
> @fcamblor @tomaswolf @ndeloof @johnou @jcarsique @stephenc @mhelff @mnencia @alanharder @olamy ? Please help us. We are using this plugin from last 6 years and after the recent Jenkins LTS upgrade it stopped working.

Any update?

**Comment by basil** [comment]
@preddymm If the changes from https://github.com/jenkinsci/scm-sync-configuration-plugin/pull/74 work, you can consider [adopting the plugin](https://www.jenkins.io/doc/developer/plugin-governance/adopt-a-plugin/) to merge and release the PR. The "[Contributing to Open Source](https://docs.google.com/document/d/1PKYIpPlRVGsBqrz0Ob1Cv3cefOZ5j2xtGZdWs27kLuw/edit#heading=h.hvd0nm6pz5o4)" workshop from DevOps World 2021 is a useful starting point for new maintainers. That document includes links to a [five part video series](https://docs.google.com/document/d/1PKYIpPlRVGsBqrz0Ob1Cv3cefOZ5j2xtGZdWs27kLuw/edit#heading=h.oz0bxvhyvna5) that illustrates many of the steps. If the plugin is crucial to your work, you may want to ask your employer to support your work efforts by allowing you to adopt the plugin.

**Comment by mdorotich** [comment]
@basil Can you reconsider fixing https://issues.jenkins.io/browse/JENKINS-66326? For non-pipeline jobs, this is our Jenkins backup mechanism.

**Comment by basil** [comment]
@mdorotich-swi If the changes from https://github.com/jenkinsci/scm-sync-configuration-plugin/pull/74 work, you can consider [adopting the plugin](https://www.jenkins.io/doc/developer/plugin-governance/adopt-a-plugin/) to merge and release the PR. The "[Contributing to Open Source](https://docs.google.com/document/d/1PKYIpPlRVGsBqrz0Ob1Cv3cefOZ5j2xtGZdWs27kLuw/edit#heading=h.hvd0nm6pz5o4)" workshop from DevOps World 2021 is a useful starting point for new maintainers. That document includes links to a [five part video series](https://docs.google.com/document/d/1PKYIpPlRVGsBqrz0Ob1Cv3cefOZ5j2xtGZdWs27kLuw/edit#heading=h.oz0bxvhyvna5) that illustrates many of the steps. If the plugin is crucial to your work, you may want to ask your employer to support your work efforts by allowing you to adopt the plugin.

**Comment by sunnyqeen** [comment]
I merged @basil #74 and fixed 2 jelly files
My build works OK with new jenkins 2.361.1
@preddymm you can try my build at 
https://github.com/sunnyqeen/scm-sync-configuration-plugin/actions/runs/3111646714
Or build yourself

**Comment by preddymm** [comment]
@sunnyqeen That's awesome.
Thank you so much!!!

**Comment by preddymm** [comment]
@sunnyqeen It's working for me on the newer Jenkins. Thanks for your fix,

**Comment by mdorotich** [comment]
@sunnyqeen thank you!
